apiVersion: v1
kind: service
matadata:
  name: post-srv
spec:
  type: NodePort
  selector:
    app: post
  ports:
    - name: posts
      protocol: TCP
      port: 4000 #port to which services will make request
      targetPort: 4000 #port on the container

